---
# network interface path
net_setting_path: /etc/network/interfaces

# bridge
br_ip_internal01: 192.168.1.0
br_ip_internal12: 192.168.2.0
br_ip_internal23: 192.168.3.0

# [variable] bridge mac address
br_mac_internal01: fe:54:00:03:e8:c2
br_mac_internal12: 0a:2c:f8:f2:a9:4b
br_mac_internal23: 1e:b6:41:91:5a:af

# network
ifname0: ens8
ifname1: ens9
netmask: 255.255.255.0

# each network address
ip_cloud_ifname1: 192.168.1.1
ip_core_edge_ifname0: 192.168.1.2
ip_core_edge_ifname1: 192.168.2.1
ip_edge_ifname0: 192.168.2.2
ip_edge_ifname1: 192.168.3.1
ip_client_ifname0: 192.168.3.2

