---
- name: insert bridge with ifname0 in /etc/network/interfaces
  blockinfile:
    dest: /etc/network/interfaces
    content: |
      auto {{ ifname0 }}
      iface {{ ifname0 }} inet static
      address {{ ip_addr.edge.ifname0 }}
      netmask {{ netmask }}

- name: insert bridge with ifname1 in /etc/network/interfaces
  blockinfile:
    dest: /etc/network/interfaces
    content: |
      auto {{ ifname1 }}
      iface {{ ifname1 }} inet static
      address {{ ip_addr.edge.ifname1 }}
      netmask {{ netmask }}

- name: add route from edge to cloud
  lineinfile:
    dest: /etc/network/interfaces
    line: up route add -net {{ br_ip.internal01 }} netmask {{ netmask }} gw {{ ip_addr.core_edge.ifname1 }}
  notify:
    - restart network with ifname0
    - restart network with ifname1

- name: add other hosts to /etc/hosts
  blockinfile:
    dest: /etc/hosts
    content: |
      {{ ip_addr.cloud.ifname1 }}   cloud
      {{ ip_addr.core_edge.ifname1 }}   core-edge
      {{ ip_addr.client.ifname0 }}   client

- name: change hostname
  command: hostnamectl set-hostname edge

