- name: Update packages.
  apt: update_cache=yes

- name: Upgrade packages.
  apt: upgrade=dist

- name: Allow port forwarding
  replace:
    dest: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward=1'
    replace: 'net.ipv4.ip_forward=1'
